import fs from "node:fs";import assert from "node:assert/strict";import {WretchedEngine} from "../src/wretched/engine.js";import {validateWretchedMvp} from "../src/wretched/model.js";import {createSeededRng} from "../src/wretched/random.js";import {ReplayRecorder,runReplay} from "../src/wretched/replay.js";import {buildTopologyView} from "../src/wretched/topology-view.js";
const data=JSON.parse(fs.readFileSync(new URL("../game/wretched-demesne.scenario-01.mvp.v0.1.json",import.meta.url)));
assert.equal(validateWretchedMvp(data).ok,true);
const g=new WretchedEngine(data,{rng:()=>0});
assert.equal(g.state.actions,3);assert.equal(g.state.hand.length,5);assert.equal(g.state.ammo,8);assert.equal(g.state.crew.name,"Security");
g.explore();assert.equal(g.state.actions,2);assert.equal(g.state.rooms.length,2);const firstRoom=g.state.crew.room;assert.deepEqual(g.legalMoves(),["entrance"]);g.move("entrance");assert.equal(g.state.crew.room,"entrance");assert.equal(g.state.actions,1);g.state.actions=3;g.move(firstRoom);assert.equal(g.state.crew.room,firstRoom);g.explore();const branchRoom=g.state.crew.room;assert.ok(g.state.connections[firstRoom].includes(branchRoom));g.state.actions=3;g.move(firstRoom);assert.deepEqual(new Set(g.legalMoves()),new Set(["entrance",branchRoom]));
g.state.crew.room="ruined-workshop";if(!g.state.rooms.includes("ruined-workshop"))g.state.rooms.push("ruined-workshop");g.search();assert.ok(g.state.inventory.includes("power-cell"));
g.state.crew.room="relay";if(!g.state.rooms.includes("relay"))g.state.rooms.push("relay");g.connect(branchRoom,"relay");g.state.actions=3;g.interact();assert.equal(g.state.relayActive,true);g.state.actions=3;assert.equal(g.move("entrance"),false);g.move(branchRoom);g.state.actions=3;g.move(firstRoom);g.state.actions=3;g.move("entrance");assert.equal(g.state.crew.room,"entrance");g.state.actions=3;g.extract();assert.equal(g.state.status,"won");
const nav=new WretchedEngine(data,{rng:()=>0});nav.state.rooms=["entrance","collapsed-gallery","flooded-passage","bone-pit"];nav.state.connections={entrance:["collapsed-gallery"],"collapsed-gallery":["entrance","flooded-passage"],"flooded-passage":["collapsed-gallery","bone-pit"],"bone-pit":["flooded-passage"]};nav.state.crew.room="bone-pit";nav.spawn("small-spider","entrance");const hunter=nav.state.enemies[0];assert.deepEqual(nav.shortestPath("entrance","bone-pit"),["entrance","collapsed-gallery","flooded-passage","bone-pit"]);nav.enemyPhase();assert.equal(hunter.room,"flooded-passage");assert.equal(nav.state.crew.currentHealth,nav.state.crew.health);nav.enemyPhase();assert.equal(hunter.room,"bone-pit");assert.ok(nav.state.crew.currentHealth<nav.state.crew.health);const stranded=new WretchedEngine(data,{rng:()=>0});stranded.state.rooms=["entrance","bone-pit"];stranded.state.crew.room="bone-pit";stranded.spawn("small-spider","entrance");stranded.enemyPhase();assert.equal(stranded.state.enemies[0].room,"entrance");
const explicit=new WretchedEngine(data,{rng:()=>0});explicit.explore();explicit.state.actions=3;explicit.move("entrance");explicit.state.actions=3;explicit.explore();assert.equal(explicit.state.crew.room,explicit.state.rooms[2]);assert.deepEqual(new Set(explicit.state.connections.entrance),new Set([explicit.state.rooms[1],explicit.state.rooms[2]]));explicit.state.actions=3;assert.equal(explicit.move(),false);assert.equal(explicit.state.crew.room,explicit.state.rooms[2]);explicit.state.crew.room="entrance";explicit.state.hand.unshift("move");explicit.state.actions=3;assert.equal(explicit.dispatch({type:"play-card",handIndex:0}),false);assert.equal(explicit.state.crew.room,"entrance");assert.equal(explicit.dispatch({type:"play-card",handIndex:0,target:explicit.state.rooms[1]}),true);assert.equal(explicit.state.crew.room,explicit.state.rooms[1]);
const h=new WretchedEngine(data,{rng:()=>0});h.spawn("small-spider","entrance");h.state.corpses.entrance=2;h.enemyPhase();assert.equal(h.state.enemies[0].fed,1);h.enemyPhase();assert.equal(h.state.enemies.length,0);assert.equal(h.state.chrysalises.length,1);h.endTurn();assert.ok(h.state.enemies.some(e=>e.id==="large-spider"));
const seed="quick-test-001";
const a=new WretchedEngine(data,{rng:createSeededRng(seed)}),b=new WretchedEngine(data,{rng:createSeededRng(seed)});
assert.deepEqual(a.snapshot(),b.snapshot());
const recGame=new WretchedEngine(data,{rng:createSeededRng(seed)});
const recorder=new ReplayRecorder(recGame,{seed});
assert.equal(recorder.dispatch({type:"explore"}),true);
assert.equal(recorder.dispatch({type:"end-turn"}),true);
const replay=recorder.toJSON();
const replayed=runReplay(data,replay);
assert.deepEqual(replayed.state,recGame.snapshot());
assert.equal(replay.steps[0].diagnostics.movement.from,"entrance");assert.ok(replay.steps[0].diagnostics.topology.added.length>0);
const branchDiag=replay.steps[0].diagnostics;assert.equal(branchDiag.revealed[0].connectedTo.includes("entrance"),true);
const corrupt=structuredClone(replay);corrupt.steps[0].state.actions=999;
let mismatch;try{runReplay(data,corrupt)}catch(e){mismatch=e}assert.match(mismatch.message,/state mismatch/);assert.equal(mismatch.step,0);assert.ok(mismatch.diff.changedTopLevel.includes("actions"));
const nonsense=structuredClone(replay);nonsense.steps[0].action={type:"move",target:"not-a-room"};
assert.throws(()=>runReplay(data,nonsense),/nonsensical\/rejected action/);
const topologyState={rooms:["entrance","bone-pit","dead-end"],crew:{room:"dead-end"},connections:{entrance:["bone-pit","dead-end"],"bone-pit":["entrance"],"dead-end":["entrance"]},corpses:{},chrysalises:[],enemies:[]};
const topologyView=buildTopologyView(topologyState);
assert.deepEqual(topologyView.edges,[{from:"entrance",to:"bone-pit"},{from:"entrance",to:"dead-end"}]);
assert.equal(topologyView.edges.some(e=>e.from==="bone-pit"&&e.to==="dead-end"),false);
assert.equal(topologyView.nodes.find(n=>n.id==="dead-end").current,true);
console.log("Wretched shared runtime, topology view, and deterministic replay tests passed.");
