import fs from "node:fs";import os from "node:os";import path from "node:path";import assert from "node:assert/strict";import {execFileSync} from "node:child_process";import {WretchedEngine} from "../src/wretched/engine.js";import {validateWretchedMvp,runtimeFromResolved} from "../src/wretched/model.js";import {createSeededRng} from "../src/wretched/random.js";import {ReplayRecorder,normalizeReplay,applyReplayCompatibility,runReplay,REPLAY_STATE_SCHEMA} from "../src/wretched/replay.js";import {buildTopologyView} from "../src/wretched/topology-view.js";
const repoRoot=new URL("../",import.meta.url);
const tempDir=fs.mkdtempSync(path.join(os.tmpdir(),"wretched-runtime-test-"));
const resolvedPath=path.join(tempDir,"resolved.json");
try{execFileSync("python",["tools/resolve_wretched_dodge.py","--out",resolvedPath],{cwd:repoRoot,stdio:"pipe"});}catch(error){process.stderr.write(error.stderr?.toString()||String(error));throw error}
const data=runtimeFromResolved(JSON.parse(fs.readFileSync(resolvedPath,"utf8")));fs.rmSync(tempDir,{recursive:true,force:true});
const betaRenderer=fs.readFileSync(new URL("../src/renderers/wretched-beta-web.js",import.meta.url),"utf8");assert.equal(betaRenderer.includes("s.relayActive"),false);assert.equal(betaRenderer.includes('s["relay-active"]'),true);assert.equal(betaRenderer.includes("Out of range"),true);
assert.equal(validateWretchedMvp(data).ok,true);
const missingStarterDecks=structuredClone(data);delete missingStarterDecks.starter_decks;assert.throws(()=>new WretchedEngine(missingStarterDecks,{rng:()=>0}),/missing resolved starter deck/);
const placementData=structuredClone(data);placementData.scenario.setup_constraints={deck_placements:[{collection_ref:"rooms",entity_ref:"bone-pit",within_last:2}]};const placementGame=new WretchedEngine(placementData,{rng:()=>0});assert.ok(placementGame.state.roomDeck.slice(-2).includes("bone-pit"));assert.equal(placementGame.state.roomDeck.filter(id=>id==="bone-pit").length,1);const g=new WretchedEngine(data,{rng:()=>0});
assert.equal(g.state.actions,3);assert.equal(g.state.hand.length,5);assert.equal(g.state.ammo,8);assert.equal(g.state.crew.name,"Security");
const reloadData=structuredClone(data);reloadData.runtime_rules.actions.reload.effects.find(e=>e.op==="add"&&e.target_ref==="ammunition").value=4;const reloadGame=new WretchedEngine(reloadData,{rng:()=>0});reloadGame.state.ammo=5;reloadGame.state.actions=3;assert.equal(reloadGame.reload(),true);assert.equal(reloadGame.state.ammo,9);assert.equal(reloadGame.state.actions,2);
g.explore();assert.equal(g.state.actions,2);assert.equal(g.state.rooms.length,2);const firstRoom=g.state.crew.room;assert.deepEqual(g.legalMoves(),["entrance"]);g.move("entrance");assert.equal(g.state.crew.room,"entrance");assert.equal(g.state.actions,1);g.state.actions=3;g.move(firstRoom);assert.equal(g.state.crew.room,firstRoom);g.explore();const branchRoom=g.state.crew.room;assert.ok(g.state.connections[firstRoom].includes(branchRoom));g.state.actions=3;g.move(firstRoom);assert.deepEqual(new Set(g.legalMoves()),new Set(["entrance",branchRoom]));
g.state.crew.room="ruined-workshop";if(!g.state.rooms.includes("ruined-workshop"))g.state.rooms.push("ruined-workshop");g.search();assert.ok(g.state.inventory.includes("power-cell"));const objectiveData=structuredClone(data);objectiveData.rule_effects["gain-power-cell"].target_ref="translation-fragment";const objectiveGame=new WretchedEngine(objectiveData,{rng:()=>0});objectiveGame.state.crew.room="ruined-workshop";objectiveGame.state.rooms.push("ruined-workshop");objectiveGame.search();assert.ok(objectiveGame.state.inventory.includes("translation-fragment"));assert.equal(objectiveGame.state.knowledge,1);assert.equal(objectiveGame.state.inventory.includes("power-cell"),false);
g.state.crew.room="relay";if(!g.state.rooms.includes("relay"))g.state.rooms.push("relay");g.connect(branchRoom,"relay");g.state.actions=3;g.interact();assert.equal(g.state["relay-active"],true);const relayData=structuredClone(data);const relayRoom=relayData.rooms.find(r=>r.id==="relay");relayRoom.interaction={requires_inventory_ref:"translation-fragment",effects:[{op:"set",target_ref:"relay-active",subject:{relative:"scenario"},value:true},{op:"add",target_ref:"threat",subject:{relative:"expedition"},value:5}]};const relayGame=new WretchedEngine(relayData,{rng:()=>0});relayGame.state.crew.room="relay";relayGame.state.rooms.push("relay");relayGame.state.inventory=["translation-fragment"];relayGame.state.actions=3;relayGame.interact();assert.equal(relayGame.state["relay-active"],true);assert.equal(relayGame.state.threat,5);g.state.actions=3;assert.equal(g.move("entrance"),false);g.move(branchRoom);g.state.actions=3;g.move(firstRoom);g.state.actions=3;g.move("entrance");assert.equal(g.state.crew.room,"entrance");g.state.actions=3;g.extract();assert.equal(g.state.status,"won");
const nav=new WretchedEngine(data,{rng:()=>0});nav.state.rooms=["entrance","collapsed-gallery","flooded-passage","bone-pit"];nav.state.connections={entrance:["collapsed-gallery"],"collapsed-gallery":["entrance","flooded-passage"],"flooded-passage":["collapsed-gallery","bone-pit"],"bone-pit":["flooded-passage"]};nav.state.crew.room="bone-pit";nav.spawn("small-spider","entrance");const hunter=nav.state.enemies[0];assert.deepEqual(nav.shortestPath("entrance","bone-pit"),["entrance","collapsed-gallery","flooded-passage","bone-pit"]);nav.enemyPhase();assert.equal(hunter.room,"flooded-passage");assert.equal(nav.state.crew.currentHealth,nav.state.crew.health);const navHealthBeforeAttack=nav.state.crew.currentHealth;nav.enemyPhase();assert.equal(hunter.room,"bone-pit");assert.equal(nav.state.crew.currentHealth,navHealthBeforeAttack-Math.max(0,hunter.attack-nav.currentDefense()));const stranded=new WretchedEngine(data,{rng:()=>0});stranded.state.rooms=["entrance","bone-pit"];stranded.state.crew.room="bone-pit";stranded.spawn("small-spider","entrance");stranded.enemyPhase();assert.equal(stranded.state.enemies[0].room,"entrance");
const explicit=new WretchedEngine(data,{rng:()=>0});explicit.state.rooms=["entrance","bone-pit","dead-end"];explicit.state.connections={entrance:["bone-pit","dead-end"],"bone-pit":["entrance"],"dead-end":["entrance"]};explicit.state.crew.room="entrance";explicit.state.hand.unshift("move");explicit.state.actions=3;assert.equal(explicit.dispatch({type:"play-card",handIndex:0}),false);assert.equal(explicit.state.crew.room,"entrance");assert.equal(explicit.dispatch({type:"play-card",handIndex:0,target:"bone-pit"}),true);assert.equal(explicit.state.crew.room,"bone-pit");
const capped=new WretchedEngine(data,{rng:()=>0});capped.state.rooms=["entrance","bone-pit","dead-end"];capped.state.connections={entrance:["bone-pit","dead-end"],"bone-pit":["entrance"],"dead-end":["entrance"]};capped.state.crew.room="entrance";capped.state.exploredFrom=["entrance"];capped.state.actions=3;const cappedDeck=[...capped.state.roomDeck];assert.equal(capped.canExplore(),false);assert.equal(capped.explore(),false);assert.equal(capped.state.actions,3);assert.deepEqual(capped.state.roomDeck,cappedDeck);const weirdData=structuredClone(data);weirdData.rules.topology.exploration_capacity.value="unbounded";const weird=new WretchedEngine(weirdData,{rng:()=>0});weird.state.rooms=["entrance","bone-pit","dead-end"];weird.state.connections={entrance:["bone-pit","dead-end"],"bone-pit":["entrance"],"dead-end":["entrance"]};weird.state.crew.room="entrance";weird.state.actions=3;assert.equal(weird.canExplore(),true);assert.equal(weird.explore(),true);assert.equal(weird.state.connections.entrance.length,3);
const threatData=structuredClone(data);threatData.runtime_rules.resources.threat.thresholds=[{at:3,effect:"Spawn test enemy.",effects:[{op:"emit",event:"spawn-enemy",payload:{entity_ref:"large-spider"}}]}];const threatGame=new WretchedEngine(threatData,{rng:()=>0});threatGame.addThreat(2);assert.equal(threatGame.state.enemies.length,0);threatGame.addThreat(1);assert.equal(threatGame.state.enemies.length,1);assert.equal(threatGame.state.enemies[0].id,"large-spider");const encounterData=structuredClone(data);encounterData.encounters=[{id:"test-encounter",name:"Test Encounter",effect:"Test structured effects.",effects:[{op:"emit",event:"spawn-enemy",payload:{entity_ref:"large-spider"}},{op:"add",target_ref:"threat",subject:{relative:"expedition"},value:3}]}];const encounterGame=new WretchedEngine(encounterData,{rng:()=>0});encounterGame.state.encounters=["test-encounter"];encounterGame.resolveEncounter();assert.equal(encounterGame.state.enemies.length,1);assert.equal(encounterGame.state.enemies[0].id,"large-spider");assert.equal(encounterGame.state.threat,3);
const salvageData=structuredClone(data);const testSalvage=salvageData.salvage.find(i=>i.id==="armor-plate");testSalvage.effects=[{op:"add",target_ref:"ammunition",subject:{relative:"expedition"},value:4},{op:"add",target_ref:"scrap",subject:{relative:"expedition"},value:5},{op:"add",target_ref:"knowledge",subject:{relative:"expedition"},value:2},{op:"add",target_ref:"health",subject:{relative:"current-actor"},value:3}];const salvageGame=new WretchedEngine(salvageData,{rng:()=>0});salvageGame.state.ammo=5;salvageGame.state.scrap=0;salvageGame.state.knowledge=0;salvageGame.state.crew.currentHealth=4;salvageGame.applySalvage(testSalvage);assert.equal(salvageGame.state.ammo,9);assert.equal(salvageGame.state.scrap,5);assert.equal(salvageGame.state.knowledge,2);assert.equal(salvageGame.state.crew.currentHealth,7);
const roomData=structuredClone(data);const testRoom=roomData.rooms.find(r=>r.id==="dead-end");testRoom.setup_effects=[{op:"emit",event:"spawn-enemy",payload:{entity_ref:"large-spider"}},{op:"add",target_ref:"spider-corpse",subject:{relative:"location"},value:3}];const roomGame=new WretchedEngine(roomData,{rng:()=>0});roomGame.resolveRoomSetup(testRoom);assert.equal(roomGame.state.enemies.length,1);assert.equal(roomGame.state.enemies[0].id,"large-spider");assert.equal(roomGame.state.enemies[0].room,"dead-end");assert.equal(roomGame.state.corpses["dead-end"],3);
const h=new WretchedEngine(data,{rng:()=>0});h.spawn("small-spider","entrance");h.state.corpses.entrance=2;h.enemyPhase();assert.equal(h.state.enemies[0].fed,1);h.enemyPhase();assert.equal(h.state.enemies.length,0);assert.equal(h.state.chrysalises.length,1);h.endTurn();assert.ok(h.state.enemies.some(e=>e.id==="large-spider"));const feedingData=structuredClone(data);feedingData.rules.spider_feeding.mechanic.chrysalis_after_feeds=1;feedingData.rules.spider_feeding.mechanic.hatch_after_end_phases=2;feedingData.rules.spider_feeding.mechanic.lineages["small-spider"]={first_feed_effects:[{op:"set",target_ref:"enemy-regeneration",value:true}],hatch_enemy_ref:"brood-mother"};const feedingGame=new WretchedEngine(feedingData,{rng:()=>0});feedingGame.spawn("small-spider","entrance");feedingGame.state.corpses.entrance=1;feedingGame.enemyPhase();assert.equal(feedingGame.state.enemies.length,0);assert.equal(feedingGame.state.chrysalises[0].hatch,"brood-mother");feedingGame.endTurn();assert.equal(feedingGame.state.enemies.some(e=>e.id==="brood-mother"),false);feedingGame.endTurn();assert.equal(feedingGame.state.enemies.some(e=>e.id==="brood-mother"),true);
const missingRuntimeData=structuredClone(data);delete missingRuntimeData.scenario.runtime.start_room_ref;assert.throws(()=>new WretchedEngine(missingRuntimeData,{rng:()=>0}),/start_room_ref/);
const scenarioRuntimeData=structuredClone(data);scenarioRuntimeData.scenario.runtime={start_room_ref:"bone-pit",extraction:{room_ref:"bone-pit",success_requires:[{state_ref:"knowledge",equals:2}],success_status:"victory-test",fallback_status:"fallback-test"}};const scenarioRuntimeGame=new WretchedEngine(scenarioRuntimeData,{rng:()=>0});assert.equal(scenarioRuntimeGame.state.crew.room,"bone-pit");assert.deepEqual(scenarioRuntimeGame.state.rooms,["bone-pit"]);scenarioRuntimeGame.state.knowledge=1;assert.equal(scenarioRuntimeGame.extract(),true);assert.equal(scenarioRuntimeGame.state.status,"fallback-test");const scenarioWinGame=new WretchedEngine(scenarioRuntimeData,{rng:()=>0});scenarioWinGame.state.knowledge=2;assert.equal(scenarioWinGame.extract(),true);assert.equal(scenarioWinGame.state.status,"victory-test");
const cardData=structuredClone(data);const triageCard=cardData.cards.find(c=>c.id==="triage");triageCard.effects=[{op:"add",target_ref:"scrap",subject:{relative:"expedition"},value:4}];const cardGame=new WretchedEngine(cardData,{rng:()=>0});cardGame.state.hand=["triage"];cardGame.state.actions=3;assert.equal(cardGame.playCard(0),true);assert.equal(cardGame.state.scrap,4);assert.equal(cardGame.state.actions,2);const suppressData=structuredClone(data);const suppressCard=suppressData.cards.find(c=>c.id==="suppressive-fire");suppressCard.effects=[{op:"subtract",target_ref:"ammunition",subject:{relative:"expedition"},value:3},{op:"add",target_ref:"threat",subject:{relative:"expedition"},value:4},{op:"set",target_ref:"suppressed",subject:{relative:"target"},value:true}];const suppressGame=new WretchedEngine(suppressData,{rng:()=>0});suppressGame.spawn("small-spider","entrance");suppressGame.state.hand=["suppressive-fire"];suppressGame.state.ammo=2;suppressGame.state.actions=3;assert.equal(suppressGame.playCard(0,0),false);assert.equal(suppressGame.state.actions,3);assert.equal(suppressGame.state.ammo,2);suppressGame.state.ammo=5;assert.equal(suppressGame.playCard(0,0),true);assert.equal(suppressGame.state.ammo,2);assert.equal(suppressGame.state.threat,4);assert.equal(suppressGame.state.enemies[0].suppressed,true);
const invocationData=structuredClone(data);const renamed=invocationData.cards.find(c=>c.id==="sidearm");renamed.id="field-test-weapon";for(const deck of Object.values(invocationData.starter_decks))for(let i=0;i<deck.length;i++)if(deck[i]==="sidearm")deck[i]="field-test-weapon";const invocationGame=new WretchedEngine(invocationData,{rng:()=>0});invocationGame.spawn("small-spider","entrance");invocationGame.state.hand=["field-test-weapon"];invocationGame.state.actions=3;assert.equal(invocationGame.playCard(0,0),true);assert.equal(invocationGame.state.actions,2);assert.equal(invocationGame.state.enemies.length,0);
const costData=structuredClone(data);costData.action_definitions.move.costs[0].amount=2;const costGame=new WretchedEngine(costData,{rng:()=>0});costGame.state.rooms=["entrance","bone-pit"];costGame.state.connections={entrance:["bone-pit"],"bone-pit":["entrance"]};costGame.state.crew.room="entrance";costGame.state.hand=["move"];costGame.state.actions=3;assert.equal(costGame.playCard(0,0,"bone-pit"),true);assert.equal(costGame.state.actions,1);
const scoutData=structuredClone(data);const scoutGame=new WretchedEngine(scoutData,{rng:()=>0});scoutGame.state.hand=["scout-ahead"];scoutGame.state.actions=3;let scoutEncounterResolutions=0;const resolveScoutEncounter=scoutGame.resolveEncounter.bind(scoutGame);scoutGame.resolveEncounter=()=>{scoutEncounterResolutions++;return resolveScoutEncounter()};assert.equal(scoutGame.playCard(0),true);const scoutedRoom=scoutGame.state.rooms.at(-1);assert.equal(scoutGame.state.crew.room,"entrance");assert.equal(scoutGame.state.encounteredRooms.includes(scoutedRoom),false,"Scout Ahead must not mark the revealed room encountered");assert.equal(scoutEncounterResolutions,0,"Scout Ahead must defer encounter resolution");scoutGame.state.actions=3;assert.equal(scoutGame.move(scoutedRoom),true);assert.equal(scoutGame.state.encounteredRooms.includes(scoutedRoom),true,"Entering a scouted room must mark it encountered");assert.equal(scoutEncounterResolutions,1,"Entering a scouted room must resolve exactly one encounter");
const coverData=structuredClone(data);const coverGame=new WretchedEngine(coverData,{rng:()=>0});coverGame.state.hand=["take-cover"];coverGame.state.actions=3;coverGame.spawn("small-spider","entrance");coverGame.state.enemies[0].attack=3;assert.equal(coverGame.playCard(0),true);assert.equal(coverGame.currentDefense(),coverGame.state.crew.defense+2);const coveredHealth=coverGame.state.crew.currentHealth;coverGame.endTurn();assert.equal(coverGame.state.crew.currentHealth,coveredHealth-Math.max(0,3-(coverGame.state.crew.defense+2)));assert.equal(coverGame.currentDefense(),coverGame.state.crew.defense);
const trainingData=structuredClone(data);const trainingGame=new WretchedEngine(trainingData,{rng:()=>0});trainingGame.state.hand=["security-training","sidearm","sidearm"];trainingGame.state.actions=3;trainingGame.spawn("large-spider","entrance");trainingGame.state.enemies[0].health=20;assert.equal(trainingGame.playCard(0),true);const hp0=trainingGame.state.enemies[0].health;assert.equal(trainingGame.playCard(0,0),true);const firstDamage=hp0-trainingGame.state.enemies[0].health;const hp1=trainingGame.state.enemies[0].health;assert.equal(trainingGame.playCard(0,0),true);const secondDamage=hp1-trainingGame.state.enemies[0].health;assert.equal(firstDamage,secondDamage+2);
const rangeData=structuredClone(data);const rangeGame=new WretchedEngine(rangeData,{rng:()=>0});rangeGame.state.rooms=["entrance","collapsed-gallery","flooded-passage","bone-pit"];rangeGame.state.connections={entrance:["collapsed-gallery"],"collapsed-gallery":["entrance","flooded-passage"],"flooded-passage":["collapsed-gallery","bone-pit"],"bone-pit":["flooded-passage"]};rangeGame.state.crew.room="entrance";rangeGame.spawn("small-spider","bone-pit");rangeGame.state.hand=["sidearm"];rangeGame.state.actions=3;assert.equal(rangeGame.playCard(0,0),false);assert.equal(rangeGame.state.actions,3);rangeGame.state.enemies[0].room="flooded-passage";assert.equal(rangeGame.playCard(0,0),true);
const locationData=structuredClone(data);
const fungal=new WretchedEngine(locationData,{rng:()=>0});fungal.state.rooms.push("fungal-vault");fungal.connect("entrance","fungal-vault");const hpBeforeFungal=fungal.state.crew.currentHealth;assert.equal(fungal.move("fungal-vault"),true);assert.equal(fungal.state.crew.currentHealth,hpBeforeFungal-1);
const fungalChoice=new WretchedEngine(locationData,{rng:()=>0});fungalChoice.state.inventory=["armor-plate"];assert.equal(fungalChoice.executeInvocation(fungalChoice.room("fungal-vault"),"enter",{choiceId:"discard-equipment",targetItem:"armor-plate"}),true);assert.equal(fungalChoice.state.inventory.includes("armor-plate"),false);
const sealed=new WretchedEngine(locationData,{rng:()=>0});sealed.state.rooms.push("sealed-door");sealed.connect("entrance","sealed-door");assert.equal(sealed.canEnter("sealed-door"),false);sealed.state.inventory.push("power-cell");assert.equal(sealed.canEnter("sealed-door"),true);
const engineerAccess=new WretchedEngine(locationData,{rng:()=>0});engineerAccess.reset("engineer");engineerAccess.state.rooms.push("sealed-door");engineerAccess.connect("entrance","sealed-door");assert.equal(engineerAccess.canEnter("sealed-door"),true);
const rock=new WretchedEngine(locationData,{rng:()=>0});rock.state.rooms.push("bone-pit");rock.connect("entrance","bone-pit");rock.state.crew.room="bone-pit";rock.state.encounters=["unstable-rock"];rock.resolveEncounter();assert.equal(rock.state.modifiers.some(m=>m.kind==="cost-adjustment"&&m.match?.action_ref==="move"&&m.match?.event==="exit-location"&&m.amount===1),true,"Unstable Rock resolved invocation must install its exit-cost modifier");assert.equal(rock.actionCost("move","exit-location"),2);rock.state.actions=3;assert.equal(rock.move("entrance"),true);assert.equal(rock.state.actions,1);
const machineEngineer=new WretchedEngine(locationData,{rng:()=>0});machineEngineer.reset("engineer");machineEngineer.state.encounters=["old-machine"];machineEngineer.resolveEncounter();assert.equal(machineEngineer.state.scrap,0);assert.equal(machineEngineer.interact(),true);assert.equal(machineEngineer.state.scrap,1);
const machineSecurity=new WretchedEngine(locationData,{rng:()=>0});machineSecurity.state.encounters=["old-machine"];machineSecurity.resolveEncounter();assert.equal(machineSecurity.state.threat,0);assert.equal(machineSecurity.interact(),true);assert.equal(machineSecurity.state.threat,1);
const fixedSearchData=structuredClone(locationData);fixedSearchData.rule_effects["gain-power-cell"].target_ref="translation-fragment";const fixedSearch=new WretchedEngine(fixedSearchData,{rng:()=>0});fixedSearch.state.crew.room="ruined-workshop";fixedSearch.state.rooms.push("ruined-workshop");assert.equal(fixedSearch.search(),true);assert.equal(fixedSearch.state.inventory.includes("translation-fragment"),true);assert.equal(fixedSearch.state.inventory.includes("power-cell"),false);
const rejectedSearch=new WretchedEngine(locationData,{rng:()=>0});rejectedSearch.state.crew.room="fungal-vault";rejectedSearch.state.rooms.push("fungal-vault");rejectedSearch.state.salvage=[];const rejectedBefore=rejectedSearch.snapshot();const rejectedRecorder=new ReplayRecorder(rejectedSearch,{seed:"rejected-action",crew:"security",captureState:true});assert.equal(rejectedRecorder.dispatch({type:"search"}),false);assert.deepEqual(rejectedSearch.snapshot(),rejectedBefore);assert.equal(rejectedRecorder.toJSON().steps.length,0);
for(const rejectedAction of [
  {type:"move",target:"not-a-room"},
  {type:"attack",enemyIndex:0,sourceRef:"sidearm"},
  {type:"play-card",handIndex:999},
  {type:"extract"},
  {type:"not-an-action"}
]){
  const atomicGame=new WretchedEngine(locationData,{rng:()=>0});
  const atomicBefore=atomicGame.snapshot();
  const atomicRecorder=new ReplayRecorder(atomicGame,{seed:"atomic-rejection",crew:"security",captureState:true});
  assert.equal(atomicRecorder.dispatch(rejectedAction),false,JSON.stringify(rejectedAction));
  assert.deepEqual(atomicGame.snapshot(),atomicBefore,JSON.stringify(rejectedAction));
  assert.equal(atomicRecorder.toJSON().steps.length,0,JSON.stringify(rejectedAction));
}
const fungalSearchData=structuredClone(locationData);const fungalSearch=new WretchedEngine(fungalSearchData,{rng:()=>0});fungalSearch.state.crew.room="fungal-vault";fungalSearch.state.rooms.push("fungal-vault");const fungalRecorder=new ReplayRecorder(fungalSearch,{seed:"fungal-search",crew:"security",captureState:true});assert.equal(fungalRecorder.dispatch({type:"search"}),true);assert.equal(fungalSearch.state.searched.includes("fungal-vault"),true);assert.equal(fungalRecorder.toJSON().steps.length,1);
const rollbackData=structuredClone(fungalSearchData);rollbackData.rooms.find(r=>r.id==="fungal-vault").invocations=rollbackData.rooms.find(r=>r.id==="fungal-vault").invocations.filter(x=>x.trigger!=="search");const rejectedFungal=new WretchedEngine(rollbackData,{rng:()=>0});rejectedFungal.state.crew.room="fungal-vault";rejectedFungal.state.rooms.push("fungal-vault");const rollbackBefore=rejectedFungal.snapshot();assert.equal(rejectedFungal.dispatch({type:"search"}),false);assert.deepEqual(rejectedFungal.snapshot(),rollbackBefore);
const replayStateBoundary=new WretchedEngine(data,{rng:()=>0});assert.equal(Object.prototype.hasOwnProperty.call(replayStateBoundary.state.crew,"invocations"),false);
const securityAbility=new WretchedEngine(data,{rng:()=>0});securityAbility.spawn("large-spider","entrance");securityAbility.state.enemies[0].health=20;securityAbility.state.hand=["sidearm","sidearm"];const sec0=securityAbility.state.enemies[0].health;assert.equal(securityAbility.playCard(0,0),true);const secFirst=sec0-securityAbility.state.enemies[0].health;const sec1=securityAbility.state.enemies[0].health;assert.equal(securityAbility.playCard(0,0),true);assert.equal(secFirst-(sec1-securityAbility.state.enemies[0].health),1);
const scoutAbility=new WretchedEngine(data,{rng:()=>0});scoutAbility.reset("scout");scoutAbility.state.rooms=["entrance","bone-pit"];scoutAbility.state.connections={entrance:["bone-pit"],"bone-pit":["entrance"]};scoutAbility.state.crew.room="entrance";const scoutActions=scoutAbility.state.actions;assert.equal(scoutAbility.move("bone-pit"),true);assert.equal(scoutAbility.state.actions,scoutActions);assert.equal(scoutAbility.move("entrance"),true);assert.equal(scoutAbility.state.actions,scoutActions-1);
assert.equal(data.scenario.players.max,1);
const regenData=structuredClone(data);regenData.enemy_runtime.regeneration_effect.value=2;const regenGame=new WretchedEngine(regenData,{rng:()=>0});regenGame.spawn("large-spider","entrance");regenGame.state.enemies[0].regeneration=true;regenGame.state.enemies[0].maxHealth=10;regenGame.state.enemies[0].health=5;regenGame.state.enemies[0].suppressed=true;regenGame.endTurn();assert.equal(regenGame.state.enemies[0].health,7);
const relayOnce=new WretchedEngine(data,{rng:()=>0});relayOnce.state.crew.room="relay";relayOnce.state.rooms.push("relay");relayOnce.state.inventory.push("power-cell");relayOnce.state.actions=3;assert.equal(relayOnce.dispatch({type:"interact"}),true);const relayAfterFirst=relayOnce.snapshot();assert.equal(relayAfterFirst["relay-active"],true);assert.equal(relayAfterFirst.threat,2);assert.deepEqual(relayAfterFirst.completedInteractions,["relay"]);assert.equal(relayOnce.dispatch({type:"interact"}),false);assert.deepEqual(relayOnce.snapshot(),relayAfterFirst);
const overrunGame=new WretchedEngine(data,{rng:()=>0});overrunGame.addThreat(12);assert.equal(overrunGame.state.status,"playing");assert.equal(overrunGame.state.overrunRound,1);overrunGame.endTurn();assert.equal(overrunGame.state.status,"lost");
const overrunEscape=new WretchedEngine(data,{rng:()=>0});overrunEscape.addThreat(12);overrunEscape.state["relay-active"]=true;overrunEscape.state.actions=3;assert.equal(overrunEscape.extract(),true);assert.equal(overrunEscape.state.status,"won");
assert.equal(data.enemy_runtime.ai_profile,"prototype-generic");
const seed="quick-test-001";
const a=new WretchedEngine(data,{rng:createSeededRng(seed)}),b=new WretchedEngine(data,{rng:createSeededRng(seed)});
assert.deepEqual(a.snapshot(),b.snapshot());
const recGame=new WretchedEngine(data,{rng:createSeededRng(seed)});
const recorder=new ReplayRecorder(recGame,{seed});
assert.equal(recorder.dispatch({type:"explore"}),true);
assert.equal(recorder.dispatch({type:"end-turn"}),true);
const replay=recorder.toJSON();
const replayed=runReplay(data,replay);
assert.deepEqual(replayed.state,recGame.snapshot());
assert.equal(replay.state_schema,REPLAY_STATE_SCHEMA);
const legacyRename=structuredClone(replay);delete legacyRename.state_schema;for(const step of legacyRename.steps){if(step.state&&Object.prototype.hasOwnProperty.call(step.state,"relay-active")){step.state.relayActive=step.state["relay-active"];delete step.state["relay-active"]}}
const legacyOriginal=structuredClone(legacyRename),normalizedLegacy=normalizeReplay(legacyRename);
assert.deepEqual(legacyRename,legacyOriginal);
assert.equal(normalizedLegacy.changed,true);
assert.equal(normalizedLegacy.migrations[0].description,"relayActive → relay-active; add replay bookkeeping defaults");
assert.deepEqual(normalizedLegacy.replay.steps[0].state.encounteredRooms,normalizedLegacy.replay.steps[0].state.rooms);
assert.deepEqual(normalizedLegacy.replay.steps[0].state.modifiers,[]);
assert.deepEqual(normalizedLegacy.replay.steps[0].state.exploredFrom,legacyRename.steps[0].state.exploredFrom??normalizedLegacy.replay.steps[0].state.exploredFrom);
// Object key insertion order is not replay semantics; migrated snapshots may add canonical keys later.
const reorderedLegacy=structuredClone(legacyRename);const reorderedState=reorderedLegacy.steps[0].state;for(const key of Object.keys(reorderedState).reverse()){const value=reorderedState[key];delete reorderedState[key];reorderedState[key]=value}
const reorderedResult=runReplay(data,reorderedLegacy);assert.equal(reorderedResult.results.length,1);assert.equal(reorderedResult.normalization.changed,true);
assert.equal(normalizedLegacy.replay.steps.every(step=>step.state?.pendingInteraction!==undefined),true);
assert.equal(normalizedLegacy.replay.steps.every(step=>Array.isArray(step.state?.completedInteractions)),true);
assert.equal(normalizedLegacy.migrations.some(m=>m.id==="runtime-state-v3"),true);
assert.equal(normalizedLegacy.migrations.some(m=>m.id==="runtime-state-v4"),true);
assert.equal(normalizedLegacy.replay.state_schema,REPLAY_STATE_SCHEMA);
assert.equal(normalizedLegacy.replay.steps.some(step=>Object.prototype.hasOwnProperty.call(step.state||{},"relayActive")),false);
const compatFixture=structuredClone(normalizedLegacy.replay);const exploreStep=compatFixture.steps.find(step=>step.action?.type==="explore");if(exploreStep?.state?.enemies?.length){const entered=exploreStep.state.crew.room,origin=(exploreStep.state.connections?.[entered]||[])[0];exploreStep.state.enemies[0].room=origin;const compatibility=applyReplayCompatibility(compatFixture,{force:true});assert.equal(compatibility.changed,true);assert.equal(compatibility.compatibility[0].kind,"semantic-compatibility-override");assert.equal(compatibility.replay.steps.find(step=>step.action?.type==="explore").state.enemies[0].room,entered)}
const normalizedReplayResult=runReplay(data,legacyRename);
assert.deepEqual(normalizedReplayResult.state,recGame.snapshot());
assert.equal(normalizedReplayResult.normalization.changed,true);
assert.equal(normalizedReplayResult.compatibility.changed,false);
const forcedCompatibilityResult=runReplay(data,legacyRename,{forceCompatibility:true});
assert.equal(forcedCompatibilityResult.normalization.changed,true);
assert.ok(forcedCompatibilityResult.compatibility);
assert.equal(forcedCompatibilityResult.compatibility.replay.state_schema,REPLAY_STATE_SCHEMA);
assert.equal(replay.steps[0].diagnostics.movement.from,"entrance");assert.ok(replay.steps[0].diagnostics.topology.added.length>0);
const branchDiag=replay.steps[0].diagnostics;assert.equal(branchDiag.revealed[0].connectedTo.includes("entrance"),true);
const corrupt=structuredClone(replay);corrupt.steps[0].state.actions=999;
let mismatch;try{runReplay(data,corrupt)}catch(e){mismatch=e}assert.match(mismatch.message,/state mismatch/);assert.equal(mismatch.step,0);assert.ok(mismatch.diff.changedTopLevel.includes("actions"));
const nonsense=structuredClone(replay);nonsense.steps[0].action={type:"move",target:"not-a-room"};
assert.throws(()=>runReplay(data,nonsense),/nonsensical\/rejected action/);
const topologyState={rooms:["entrance","bone-pit","dead-end"],crew:{room:"dead-end"},connections:{entrance:["bone-pit","dead-end"],"bone-pit":["entrance"],"dead-end":["entrance"]},corpses:{},chrysalises:[],enemies:[]};
const topologyView=buildTopologyView(topologyState);
assert.deepEqual(topologyView.edges,[{from:"entrance",to:"bone-pit"},{from:"entrance",to:"dead-end"}]);
assert.equal(topologyView.edges.some(e=>e.from==="bone-pit"&&e.to==="dead-end"),false);
assert.equal(topologyView.nodes.find(n=>n.id==="dead-end").current,true);
console.log("Wretched shared runtime, topology view, and deterministic replay tests passed.");
